// TAB boostsets
// ----------------------------------------------------------------------------------------------
// Source File : Defs/boostsets/_src/BoostSets.xls 
// Sheet : boostsets 
//
// Script      : xlstoboostsetdef.bat 
// Version     : 1 
// ----------------------------------------------------------------------------------------------

// DisplayName :
"P1606305053" "Display Test Boost Set"
// DisplayText :
"P2458647327" "Freakshow disguise that gives extra range!"
// DisplayText :
"P226321035" "Stamina!"
// TAB boostsets
// ----------------------------------------------------------------------------------------------
// Source File : data/Defs/boostsets/_src/BoostSets.xls 
// Sheet : boostsets 
//
// Script      : xlstoboostsetdef.bat 
// Version     : 2 
// ----------------------------------------------------------------------------------------------

// DisplayName :
"P83626102" "Bonesnap"
// GroupName :
"P616951717" "Melee Damage"
// DisplayName :
"P1465747032" "Pulverizing Fisticuffs"
// DisplayName :
"P3735782856" "Bruising Blow"
// DisplayName :
"P4260465571" "Pounding Slugfest"
// DisplayName :
"P2892077945" "Smashing Haymaker"
// DisplayName :
"P1514120885" "Kinetic Combat"
// DisplayName :
"P348355974" "Focused Smite"
// DisplayName :
"P3356177460" "Touch of Death"
// DisplayName :
"P861957004" "Crushing Impact"
// DisplayName :
"P2592997325" "Mako's Bite"
// DisplayName :
"P2166787892" "Hecatomb"
// DisplayName :
"P3397962759" "Gladiator's Strike"
// DisplayName :
"P3650433933" "Blistering Cold"
// DisplayName :
"P2562448669" "Superior Blistering Cold"
// DisplayName :
"P1727986675" "Far Strike"
// GroupName :
"P2223860936" "Ranged Damage"
// DisplayName :
"P4254054842" "Salvo"
// DisplayName :
"P1357249065" "Volley Fire"
// DisplayName :
"P3408457872" "Tempest"
// DisplayName :
"P3843046770" "Maelstrom's Fury"
// DisplayName :
"P364084948" "Entropic Chaos"
// DisplayName :
"P2358001401" "Ruin"
// DisplayName :
"P2062197804" "Decimation"
// DisplayName :
"P40241163" "Thunderstrike"
// DisplayName :
"P2688984339" "Devastation"
// DisplayName :
"P3854142415" "Apocalypse"
// DisplayName :
"P1505641644" "Gladiator's Javelin"
// DisplayName :
"P2309197542" "Winter's Bite"
// DisplayName :
"P1920512285" "Superior Winter's Bite"
// DisplayName :
"P1863840826" "Air Burst"
// GroupName :
"P3502029540" "Targeted AoE Damage"
// DisplayName :
"P1171036302" "Detonation"
// DisplayName :
"P387932133" "Positron's Blast"
// DisplayName :
"P4090607386" "Annihilation"
// DisplayName :
"P3786286960" "Ragnarok"
// DisplayName :
"P2166222718" "Javelin Volley"
// DisplayName :
"P1133192876" "Frozen Blast"
// DisplayName :
"P1291368691" "Superior Frozen Blast"
// DisplayName :
"P1572276521" "Cleaving Blow"
// GroupName :
"P1671220172" "PBAoE Damage"
// DisplayName :
"P1123872506" "Multi-Strike"
// DisplayName :
"P1979853608" "Scirocco's Dervish"
// DisplayName :
"P2021851359" "Armageddon"
// DisplayName :
"P2093574217" "Eradication"
// DisplayName :
"P2129333331" "Obliteration"
// DisplayName :
"P4193685226" "Fury of the Gladiator"
// DisplayName :
"P1358356015" "Avalanche"
// DisplayName :
"P645618330" "Superior Avalanche"
// DisplayName :
"P1800097606" "Exploit Weakness"
// GroupName :
"P771149067" "Sniper Attacks"
// DisplayName :
"P2397805828" "Calibrated Accuracy"
// DisplayName :
"P1327258948" "Executioner's Contract"
// DisplayName :
"P234970101" "Extreme Measures"
// DisplayName :
"P3782889485" "Sting of the Manticore"
// DisplayName :
"P1208591680" "Unquestioning Loyalty"
// GroupName :
"P2234567739" "Pet Damage"
// DisplayName :
"P3818669338" "Commanding Presence"
// DisplayName :
"P535966994" "Brilliant Leadership"
// DisplayName :
"P665979883" "Edict of the Master"
// DisplayName :
"P3699690009" "Blood Mandate"
// DisplayName :
"P2560246257" "Sovereign Right"
// DisplayName :
"P4160714120" "Soulbound Allegiance"
// DisplayName :
"P980809230" "Call to Arms"
// GroupName :
"P3840077829" "Recharge Intensive Pets"
// DisplayName :
"P3791994583" "Expedient Reinforcement"
// DisplayName :
"P742160639" "Karma"
// GroupName :
"P642123166" "Defense Sets"
// DisplayName :
"P278365263" "Kismet"
// DisplayName :
"P8520840" "Serendipity"
// DisplayName :
"P4011955253" "Gift of the Ancients"
// DisplayName :
"P2090734941" "Red Fortune"
// DisplayName :
"P1235770269" "Luck of the Gambler"
// DisplayName :
"P3915507354" "Reactive_Defenses"
// DisplayName :
"P3992952942" "Shield Wall"
// DisplayName :
"P570592680" "Steadfast Protection"
// GroupName :
"P42300052" "Resist Damage"
// DisplayName :
"P858309208" "Impervious Skin"
// DisplayName :
"P1817357421" "Reactive Armor"
// DisplayName :
"P1329428347" "Impervium Armor"
// DisplayName :
"P4185941761" "Titanium Coating"
// DisplayName :
"P1612546811" "Aegis"
// DisplayName :
"P3524615423" "Unbreakable Guard"
// DisplayName :
"P2205543829" "Gladiator's Armor"
// DisplayName :
"P3637206485" "Triage"
// GroupName :
"P220831749" "Healing"
// DisplayName :
"P4043781476" "Regenerative Tissue"
// DisplayName :
"P971392213" "Harmonized Healing"
// DisplayName :
"P2712938009" "Miracle"
// DisplayName :
"P225459190" "Doctored Wounds"
// DisplayName :
"P423431395" "Numina's Convalesence"
// DisplayName :
"P4012723841" "Preventive_Medicine"
// DisplayName :
"P1783394543" "Panacea"
// DisplayName :
"P2317424933" "Theft of Essence"
// GroupName :
"P500425294" "Accurate Healing"
// DisplayName :
"P3286062499" "Touch of the Nictus"
// DisplayName :
"P936425106" "Paralytic"
// GroupName :
"P3531333568" "Holds"
// DisplayName :
"P2896106676" "Neuronic Shutdown"
// DisplayName :
"P3869003373" "Essence of Curare"
// DisplayName :
"P2227746146" "Ghost Widow's Embrace"
// DisplayName :
"P3798893072" "Unbreakable Constraint"
// DisplayName :
"P1875932060" "Basilisk's Gaze"
// DisplayName :
"P829759422" "Lockdown"
// DisplayName :
"P1669398830" "Gladiator's Net"
// DisplayName :
"P1460617054" "Entomb"
// DisplayName :
"P1943041291" "Superior Entomb"
// DisplayName :
"P1102992853" "Stagger"
// GroupName :
"P2363233992" "Stuns"
// DisplayName :
"P1544714467" "Razzle Dazzle"
// DisplayName :
"P1678567685" "Rope A Dope"
// DisplayName :
"P1082323411" "Stupefy"
// DisplayName :
"P1671735844" "Absolute Amazement"
// DisplayName :
"P515263503" "Rooting Grasp"
// GroupName :
"P529984861" "Immobilize"
// DisplayName :
"P892062106" "Debilitative Action"
// DisplayName :
"P2487517276" "Enfeebled Operation"
// DisplayName :
"P1621075447" "Trap of the Hunter"
// DisplayName :
"P737297741" "Gravitational Anchor"
// DisplayName :
"P2295857341" "Curtail Speed"
// GroupName :
"P3129357468" "Slow Movement"
// DisplayName :
"P4076384703" "Impeded Swiftness"
// DisplayName :
"P1527563023" "Tempered Readiness"
// DisplayName :
"P974407973" "Pacing of the Turtle"
// DisplayName :
"P3556493781" "Hibernation"
// GroupName :
"P2871861558" "Sleep"
// DisplayName :
"P3867718210" "Induced Coma"
// DisplayName :
"P3108202878" "Lethargic Repose"
// DisplayName :
"P2971135820" "Call of the Sandman"
// DisplayName :
"P28589024" "Fortunata Hypnosis"
// DisplayName :
"P2582720998" "Horror"
// GroupName :
"P2710656193" "Fear"
// DisplayName :
"P4188797130" "Unspeakable Terror"
// DisplayName :
"P1336353347" "Nightmare"
// DisplayName :
"P1902236141" "Glimpse of the Abyss"
// DisplayName :
"P2211205642" "Befuddling Aura"
// GroupName :
"P1943204847" "Confuse"
// DisplayName :
"P3763794352" "Cacophany"
// DisplayName :
"P1962185056" "Perplex"
// DisplayName :
"P3935840015" "Malaise's Illusions"
// DisplayName :
"P2277276400" "Coercive Persuasion "
// DisplayName :
"P1465449429" "Soaring"
// GroupName :
"P1824032808" "Flight"
// DisplayName :
"P1278240141" "Freebird"
// DisplayName :
"P4023185823" "Springfoot"
// GroupName :
"P745788540" "Leaping"
// DisplayName :
"P825162638" "Unbounded Leap"
// DisplayName :
"P3872647892" "Quickfoot"
// GroupName :
"P203092125" "Running"
// DisplayName :
"P2118179343" "Celerity"
// DisplayName :
"P1329908654" "Jaunt"
// GroupName :
"P1483340788" "Teleport"
// DisplayName :
"P2257011414" "Time & Space Manipulation"
// DisplayName :
"P3145524272" "Blessing of the Zephyr"
// GroupName :
"P1446595715" "Universal Travel"
// DisplayName :
"P221795736" "Winter's Gift"
// DisplayName :
"P1020008044" "Annoyance"
// GroupName :
"P1989716037" "Taunt"
// DisplayName :
"P219657449" "Triumphant Insult"
// DisplayName :
"P1710123266" "Mocking Beratement"
// DisplayName :
"P112646202" "Perfect Zinger"
// DisplayName :
"P2456930215" "Volley of Velocity"
// GroupName :
"P4021946583" "Knockback"
// DisplayName :
"P295802836" "Explosive Strike"
// DisplayName :
"P2845553854" "Kinetic Crash"
// DisplayName :
"P2737702752" "Force Feedback"
// DisplayName :
"P1983748070" "Adrenal Adjustment"
// GroupName :
"P1327380731" "Endurance Modification"
// DisplayName :
"P97879276" "Energy Manipulator"
// DisplayName :
"P815836497" "Efficacy Adaptor"
// DisplayName :
"P3730166671" "Performance Shifter"
// DisplayName :
"P168790400" "Encouraged Accuracy"
// GroupName :
"P242233904" "To Hit Buff"
// DisplayName :
"P798000468" "Rectified Reticle"
// DisplayName :
"P3812456576" "Adjusted Targeting"
// DisplayName :
"P227405659" "Gaussian's Synchronized Fire-Control"
// DisplayName :
"P3532737761" "Discouraging Words"
// GroupName :
"P272022069" "To Hit Debuff"
// DisplayName :
"P2108806579" "Deflated Ego"
// DisplayName :
"P620549654" "Dampened Spirits"
// DisplayName :
"P2720420439" "Dark Watcher's Despair"
// DisplayName :
"P2342231082" "Exploited Vulnerability"
// GroupName :
"P664228037" "Defense Debuff"
// DisplayName :
"P2153023494" "Achilles' Heel"
// DisplayName :
"P476075962" "Undermined Defenses"
// DisplayName :
"P2051441160" "Touch of Lady Grey"
// DisplayName :
"P3818259512" "Shield Breaker"
// GroupName :
"P1905706306" "Accurate Defense Debuff"
// DisplayName :
"P1349527124" "Analyze Weakness"
// DisplayName :
"P1912163845" "Cloud Senses"
// GroupName :
"P1019748334" "Accurate To-Hit Debuff"
// DisplayName :
"P1373336988" "Siphon Insight"
// DisplayName :
"P1320680603" "Blaster's Wrath"
// GroupName :
"P2249135353" "Blaster Archetype Sets"
// DisplayName :
"P261689867" "Superior Blaster's Wrath"
// DisplayName :
"P160445125" "Defiant Barrage"
// DisplayName :
"P1220467797" "Superior Defiant Barrage"
// DisplayName :
"P2231345421" "Will of the Controller"
// GroupName :
"P3307912099" "Controller Archetype Sets"
// DisplayName :
"P438305790" "Superior Will of the Controller"
// DisplayName :
"P3268671492" "Overpowering Presence"
// DisplayName :
"P2045028355" "Superior Overpowering Presence"
// DisplayName :
"P3537944822" "Defender's Bastion"
// GroupName :
"P807208903" "Defender Archetype Sets"
// DisplayName :
"P869837802" "Superior Defender's Bastion"
// DisplayName :
"P119996832" "Vigilant Assault"
// DisplayName :
"P4150901770" "Superior Vigilant Assault"
// DisplayName :
"P1623964531" "Scrapper's Strike"
// GroupName :
"P1998534311" "Scrapper Archetype Sets"
// DisplayName :
"P1446559544" "Superior Scrapper's Strike"
// DisplayName :
"P3267964990" "Critical Strikes"
// DisplayName :
"P847744404" "Superior Critical Strikes"
// DisplayName :
"P1135183378" "Might of the Tanker"
// GroupName :
"P3922535310" "Tanker Archetype Sets"
// DisplayName :
"P1464459830" "Superior Might of the Tanker"
// DisplayName :
"P3752842811" "Gauntleted Fist"
// DisplayName :
"P2659268779" "Superior Gauntleted Fist"
// DisplayName :
"P4045402937" "Kheldian's Grace"
// GroupName :
"P571553260" "Kheldian Archetype Sets"
// DisplayName :
"P22105747" "Superior Kheldian's Grace"
// DisplayName :
"P1110006839" "Essence Transfer"
// DisplayName :
"P2993152413" "Superior Essence Transfer"
// DisplayName :
"P1343719276" "Brute's Fury"
// GroupName :
"P3956005688" "Brute Archetype Sets"
// DisplayName :
"P1600395571" "Superior Brute's Fury"
// DisplayName :
"P1816735174" "Unrelenting Fury"
// DisplayName :
"P2617741420" "Superior Unrelenting Fury"
// DisplayName :
"P3616372707" "Malice of the Corruptor"
// GroupName :
"P124561899" "Corruptor Archetype Sets"
// DisplayName :
"P4087811047" "Superior Malice of the Corruptor"
// DisplayName :
"P3022129140" "Scourging Blast"
// DisplayName :
"P4111264100" "Superior Scourging Blast"
// DisplayName :
"P1767096646" "Ascendency of the Dominator"
// GroupName :
"P120307868" "Dominator Archetype Sets"
// DisplayName :
"P3904040924" "Superior Ascendency of the Dominator"
// DisplayName :
"P557004466" "Dominating Grasp"
// DisplayName :
"P3514665752" "Superior Dominating Grasp"
// DisplayName :
"P2118122973" "Command of the Mastermind"
// GroupName :
"P2483818269" "Mastermind Archetype Sets"
// DisplayName :
"P1138762212" "Superior Command of the Mastermind"
// DisplayName :
"P2969075381" "Mark of Supremacy"
// DisplayName :
"P2248899326" "Superior Mark of Supremacy"
// DisplayName :
"P3006364639" "Stalker's Guile"
// GroupName :
"P3225314016" "Stalker Archetype Sets"
// DisplayName :
"P4062156111" "Superior Stalker's Guile"
// DisplayName :
"P1645339878" "Assassin's Mark"
// DisplayName :
"P591334006" "Superior Assassin's Mark"
// DisplayName :
"P100306470" "Dominion of Arachnos"
// GroupName :
"P2611858036" "Soldiers of Arachnos Archetype Sets"
// DisplayName :
"P971868819" "Superior Dominion of Arachnos"
// DisplayName :
"P2046001291" "Spider's Bite"
// DisplayName :
"P2183708528" "Superior Spider's Bite"
// DisplayName :
"P1712995004" "Overwhelming Force"
// GroupName :
"P2765653189" "Universal Damage Sets"
