
"GoldLock",			"Sorry, you need a Gold Club card to get into this party."
"PocketDSkiResortClosed",	"This door is locked currently. A small sign hangs on the handle reading, Closed for the Off-Season."
"PraetorianLock",		"As a Praetorian visitor, you may only access certain areas in Pocket D.  You may not leave the premises."
"BlueDoorWarning_PocketD",	"<color deepskyblue>The passage in front of you leads to Paragon City. Here you will find both Heroes who combat great evils and Vigilantes who do what they must to maintain the peace.  Are you brave enough to face the challenges of this city of heroes?</color>"
"RedDoorWarning_PocketD",	"<color red>The passage in front of you leads to the Rogue Isles.  Throughout the Isles, you’ll find Villains performing heinous deeds and Rogues who think of no one other than themselves.  Are you strong enough to take on the dangers of this city of villains?</color>"
"NoAccessToNonPraetorians",	"A dimensional field surrounds this door.  You cannot enter."