
"UIC_NoResistance"	"This entrance to the surface requires a passcode known only to Loyalists."
"UIC_NoLoyalist"	"This entrance to the surface has been reprogrammed to use Resistance codes."
"UIC_WelcomeResistance"	"This entrance to the surface requires you to enter your Resistance passcode. Do you want to do this and proceed to Imperial City?"
"UIC_WelcomeLoyalist"	"This entrance to the surface requires you to enter your Loyalist passcode. Do you want to do this and proceed to Imperial City?"
"UIC_ResHub_ForRes"	"This is the entrance to the underground Resistance Base in Imperial City. Do you want to enter?"
"UIC_ResHub_ForLoy"	"This door seems to require some secret passcode to open; a passcode you lack."