
"UNT_NoResistance"	"This entrance to the surface requires a passcode known only to Loyalists."
"UNT_NoLoyalist"	"This entrance to the surface has been reprogrammed to use Resistance codes."
"UNT_WelcomeResistance"	"This entrance to the surface requires you to enter your Resistance passcode. Do you want to do this and proceed to Neutropolis?"
"UNT_WelcomeLoyalist"	"This entrance to the surface requires you to enter your Loyalist passcode. Do you want to do this and proceed to Neutropolis?"
"UNT_ResHub_ForRes"	"This is the entrance to the underground Resistance Base in Neutropolis. Do you want to enter?"
"UNT_ResHub_ForLoy"	"This door is secured with a secret passcode and does not open."