
"IC_NoResistance"	"This entrance to the Underground requires a passcode known only to Loyalists."
"IC_NoLoyalist"		"This entrance to the Underground has been reprogrammed to only use Resistance codes."
"IC_WelcomeResistance"	"This entrance to the Underground requires you to enter your Resistance passcode. Do you want to do this and proceed to Underground Imperial City?"
"IC_WelcomeLoyalist"	"This entrance to the Underground requires you to enter your Loyalist passcode. Do you want to do this and proceed to Underground Imperial City?"
"IC_SyndicateLock"	"This door's passcode reader appears to have been hacked. You cannot enter."
"TUNNELHero"		"Villains are not allowed to pass."
"TUNNELVillain"		"Heroes are not allowed to pass."
"PraetorianTUNNELLock"	"As a Praetorian Loyalist or Resistance Member, you are not prepared for what lies beyond this portal."