
"NT_NoResistance"	"This entrance to the Underground requires a passcode known only to Loyalists."
"NT_NoLoyalist"		"This entrance to the Underground has been reprogrammed to use Resistance codes."
"NT_WelcomeResistance"	"This entrance to the Underground requires you to enter your Resistance passcode. Do you want to do this and proceed to Underground Neutropolis?"
"NT_WelcomeLoyalist"	"This entrance to the Underground requires you to enter your Loyalist passcode. Do you want to do this and proceed to Underground Neutropolis?"