
"UNP_NoResistance"	"This entrance to the surface requires a passcode known only to Loyalists."
"UNP_NoLoyalist"	"This entrance to the surface has been reprogrammed to use Resistance codes only."
"UNP_WelcomeResistance"	"This entrance to the surface requires you to enter your Resistance passcode. Do you want to do this and proceed to Nova Praetoria?"
"UNP_WelcomeLoyalist"	"This entrance to the surface requires you to enter your Loyalist passcode. Do you want to do this and proceed to Nova Praetoria?"
"UNP_ResHub_ForRes"	"This is the entrance to the underground Resistance Base in Nova Praetoria. Do you want to enter?"
"UNP_ResHub_ForLoy"	"This door seems to require some secret passcode to open."