
"DoorColiseum" "The current showing of 'Time Gladiator' has not yet let out."
"DoorCasino" "The current showing of 'The Casino Heist' has not yet let out."
"DoorBogus1" "The current showing of 'Soldiers with Big Guns' has not yet let out."
"DoorBogus2" "The current showing of 'Please Give Me An Award For This film' has not yet let out."
"DoorRoleSelect" "Please select a role from one of the nearby movie posters before entering 'The Casino Heist'."
"DoorBogus3" "'Theater Employees Only.'"
"DoorVent" "There's not enough time to make it to the vault!"