//
// Generated by xlstorooms.bat ver 2
//

Plot TEST_PLOT
{
	DisplayName "P3325706387"
	Length 24
	Width 28
	MaxRaidParty 32
	DisplayTabName "P2018365746"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
	}
	GroupName Base_LandPlot4x4_32
	Requires accesslevel char> 0 >
	CostPrestige 1000000000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P2206248382"
	DisplayShortHelp "P4037896308"
}

Plot TinyHiddenSpot_8x8
{
	DisplayName "P2687200195"
	Length 8
	Width 8
	MaxRaidParty 8
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 0
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P732501349"
	DisplayShortHelp "P3406086671"
}

Plot SmallHiddenSpot_8x12
{
	DisplayName "P928915704"
	Length 8
	Width 12
	MaxRaidParty 8
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 84500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3773531649"
	DisplayShortHelp "P3322454692"
}

Plot HiddenSpot_12x12
{
	DisplayName "P1831153704"
	Length 12
	Width 12
	MaxRaidParty 8
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 312500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P1580420700"
	DisplayShortHelp "P1728804902"
}

Plot SmallSecretLocation_12x16
{
	DisplayName "P3625742050"
	Length 12
	Width 16
	MaxRaidParty 8
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 722000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3280326592"
	DisplayShortHelp "P988227882"
}

Plot SecretLocation_16x16
{
	DisplayName "P2770037980"
	Length 16
	Width 16
	MaxRaidParty 16
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 1250000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3280326592"
	DisplayShortHelp "P592160305"
}

Plot LargeSecretLocation_16x20
{
	DisplayName "P548308187"
	Length 16
	Width 20
	MaxRaidParty 16
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 1984500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3280326592"
	DisplayShortHelp "P3144049848"
}

Plot SmallHiddenComplex_20x20
{
	DisplayName "P983834371"
	Length 20
	Width 20
	MaxRaidParty 24
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 2812500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3280326592"
	DisplayShortHelp "P1389970807"
}

Plot HiddenComplex_20x24
{
	DisplayName "P976785548"
	Length 20
	Width 24
	MaxRaidParty 24
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 3872000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P330834585"
	DisplayShortHelp "P255136891"
}

Plot LargeHiddenComplex_24x24
{
	DisplayName "P3940569054"
	Length 24
	Width 24
	MaxRaidParty 32
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 5000000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P330834585"
	DisplayShortHelp "P379165536"
}

Plot MassiveHiddenComplex_24x28
{
	DisplayName "P733722559"
	Length 24
	Width 28
	MaxRaidParty 32
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 6384500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P458055360"
	DisplayShortHelp "P4037896308"
}

Plot SmallSecureLocation_12x16
{
	DisplayName "P3810901235"
	Length 12
	Width 16
	MaxRaidParty 8
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 3
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 722000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P4104070337"
	DisplayShortHelp "P988227882"
}

Plot SecureLocation_16x16
{
	DisplayName "P2653077197"
	Length 16
	Width 16
	MaxRaidParty 16
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 3
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 1250000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P4104070337"
	DisplayShortHelp "P592160305"
}

Plot LargeSecureLocation_16x20
{
	DisplayName "P462902986"
	Length 16
	Width 20
	MaxRaidParty 16
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 4
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 1984500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P4104070337"
	DisplayShortHelp "P3144049848"
}

Plot SmallSecureComplex_20x20
{
	DisplayName "P3579008945"
	Length 20
	Width 20
	MaxRaidParty 24
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 4
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 2812500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P4104070337"
	DisplayShortHelp "P1389970807"
}

Plot SecureComplex_20x24
{
	DisplayName "P3587168318"
	Length 20
	Width 24
	MaxRaidParty 24
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 5
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 5000000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3626149926"
	DisplayShortHelp "P255136891"
}

Plot LargeSecureComplex_24x24
{
	DisplayName "P85395308"
	Length 24
	Width 24
	MaxRaidParty 32
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 5
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 7812500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3626149926"
	DisplayShortHelp "P379165536"
}

Plot MassiveSecureComplex_24x28
{
	DisplayName "P3293380365"
	Length 24
	Width 28
	MaxRaidParty 32
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 6
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	Requires x
	CostPrestige 11250000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P2459140217"
	DisplayShortHelp "P4037896308"
}

Plot SmallHiddenSpot_8x12_I14
{
	DisplayName "P928915704"
	Length 8
	Width 12
	MaxRaidParty 8
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 84500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3773531649"
	DisplayShortHelp "P3322454692"
}

Plot HiddenSpot_12x12_I14
{
	DisplayName "P1831153704"
	Length 12
	Width 12
	MaxRaidParty 8
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 312500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P1580420700"
	DisplayShortHelp "P1728804902"
}

Plot SmallSecretLocation_12x16_I14
{
	DisplayName "P3625742050"
	Length 12
	Width 16
	MaxRaidParty 8
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 722000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3280326592"
	DisplayShortHelp "P988227882"
}

Plot SecretLocation_16x16_I14
{
	DisplayName "P2770037980"
	Length 16
	Width 16
	MaxRaidParty 16
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 1250000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3280326592"
	DisplayShortHelp "P592160305"
}

Plot LargeSecretLocation_16x20_I14
{
	DisplayName "P548308187"
	Length 16
	Width 20
	MaxRaidParty 16
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 1984500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3280326592"
	DisplayShortHelp "P3144049848"
}

Plot SmallHiddenComplex_20x20_I14
{
	DisplayName "P983834371"
	Length 20
	Width 20
	MaxRaidParty 24
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 2812500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3280326592"
	DisplayShortHelp "P1389970807"
}

Plot HiddenComplex_20x24_I14
{
	DisplayName "P976785548"
	Length 20
	Width 24
	MaxRaidParty 24
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 3872000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P330834585"
	DisplayShortHelp "P255136891"
}

Plot LargeHiddenComplex_24x24_I14
{
	DisplayName "P3940569054"
	Length 24
	Width 24
	MaxRaidParty 32
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 5000000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P330834585"
	DisplayShortHelp "P379165536"
}

Plot MassiveHiddenComplex_24x28_I14
{
	DisplayName "P733722559"
	Length 24
	Width 28
	MaxRaidParty 32
	DisplayTabName "P2414996619"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 1
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 1
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 1
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
		Limit 1
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 6384500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P458055360"
	DisplayShortHelp "P4037896308"
}

Plot SmallSecureLocation_12x16_I14
{
	DisplayName "P3810901235"
	Length 12
	Width 16
	MaxRaidParty 8
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 3
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 722000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P4104070337"
	DisplayShortHelp "P988227882"
}

Plot SecureLocation_16x16_I14
{
	DisplayName "P2653077197"
	Length 16
	Width 16
	MaxRaidParty 16
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 3
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 1250000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P4104070337"
	DisplayShortHelp "P592160305"
}

Plot LargeSecureLocation_16x20_I14
{
	DisplayName "P462902986"
	Length 16
	Width 20
	MaxRaidParty 16
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 4
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 1984500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P4104070337"
	DisplayShortHelp "P3144049848"
}

Plot SmallSecureComplex_20x20_I14
{
	DisplayName "P3579008945"
	Length 20
	Width 20
	MaxRaidParty 24
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 4
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 2812500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P4104070337"
	DisplayShortHelp "P1389970807"
}

Plot SecureComplex_20x24_I14
{
	DisplayName "P3587168318"
	Length 20
	Width 24
	MaxRaidParty 24
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 5
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 5000000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3626149926"
	DisplayShortHelp "P255136891"
}

Plot LargeSecureComplex_24x24_I14
{
	DisplayName "P85395308"
	Length 24
	Width 24
	MaxRaidParty 32
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 5
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 7812500
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P3626149926"
	DisplayShortHelp "P379165536"
}

Plot MassiveSecureComplex_24x28_I14
{
	DisplayName "P3293380365"
	Length 24
	Width 28
	MaxRaidParty 32
	DisplayTabName "P829579058"
	DetailAllowed Defense
	{
	}
	DetailAllowed DefenseAux
	{
	}
	DetailAllowed Medical
	{
	}
	DetailAllowed MedicalAux
	{
	}
	DetailAllowed Control
	{
		Limit 2
	}
	DetailAllowed ControlAux
	{
	}
	DetailAllowed Energy
	{
		Limit 2
	}
	DetailAllowed EnergyAux
	{
	}
	DetailAllowed Battery
	{
		Limit 6
	}
	DetailAllowed Teleport
	{
	}
	DetailAllowed TeleportAux
	{
	}
	DetailAllowed Storage
	{
		Limit 18
	}
	DetailAllowed Workshop
	{
		Limit 6
	}
	DetailAllowed WorkshopAux
	{
	}
	DetailAllowed ItemsOfPower
	{
	}
	DetailAllowed Empowerment
	{
		Limit 6
	}
	DetailAllowed EnergyControl
	{
		Limit 1
	}
	DetailAllowed Anchor
	{
		Limit 6
	}
	DetailAllowed Entrance
	{
		Limit 1
	}
	DetailAllowed Decorative
	{
		Limit 20000
	}
	GroupName Base_LandPlot4x4_32
	CostPrestige 11250000
	UpkeepPrestige 0
	CostInfluence 0
	UpkeepInfluence 0
	DisplayHelp "P2459140217"
	DisplayShortHelp "P4037896308"
}

