//
// Generated by xlstoitems.bat ver 15
//

DetailCategory Anchor
{
	DisplayName  "P1627198539"
	EnergyPriority 21
	ControlPriority 21
}
DetailCategory Battery
{
	DisplayName  "P529780018"
	EnergyPriority 19
	ControlPriority 19
}
DetailCategory Control
{
	DisplayName  "P577115607"
	EnergyPriority 6
	ControlPriority 6
}
DetailCategory ControlAux
{
	DisplayName  "P3138489878"
	EnergyPriority 7
	ControlPriority 7
}
DetailCategory Decorative
{
	DisplayName  "P1156312807"
	EnergyPriority 20
	ControlPriority 20
}
DetailCategory Defense
{
	DisplayName  "P337169641"
	EnergyPriority 8
	ControlPriority 8
}
DetailCategory DefenseAux
{
	DisplayName  "P1471925978"
	EnergyPriority 9
	ControlPriority 9
}
DetailCategory Empowerment
{
	DisplayName  "P3360419001"
	EnergyPriority 24
	ControlPriority 24
}
DetailCategory Energy
{
	DisplayName  "P2428337319"
	EnergyPriority 22
	ControlPriority 22
}
DetailCategory EnergyAux
{
	DisplayName  "P3498774609"
	EnergyPriority 23
	ControlPriority 23
}
DetailCategory EnergyControl
{
	DisplayName  "P2916030754"
	EnergyPriority 5
	ControlPriority 5
}
DetailCategory Entrance
{
	DisplayName  "P2125202399"
	EnergyPriority 18
	ControlPriority 18
}
DetailCategory ItemsOfPower
{
	DisplayName  "P3125742652"
	EnergyPriority 17
	ControlPriority 17
}
DetailCategory Medical
{
	DisplayName  "P3093708486"
	EnergyPriority 3
	ControlPriority 3
}
DetailCategory MedicalAux
{
	DisplayName  "P2004250039"
	EnergyPriority 4
	ControlPriority 4
}
DetailCategory Storage
{
	DisplayName  "P2613519016"
	EnergyPriority 16
	ControlPriority 16
}
DetailCategory Teleport
{
	DisplayName  "P569504987"
	EnergyPriority 11
	ControlPriority 11
}
DetailCategory TeleportAux
{
	DisplayName  "P48763820"
	EnergyPriority 12
	ControlPriority 12
}
DetailCategory Workshop
{
	DisplayName  "P1645830290"
	EnergyPriority 1
	ControlPriority 1
}
DetailCategory WorkshopAux
{
	DisplayName  "P2610604043"
	EnergyPriority 2
	ControlPriority 2
}
