
# some translations from i24 that are missing in 2400

"P2906792940", "Flying Strike"
"P3234427922", "Charge (Targeted AoE), High DMG(Smash), Foe Knockdown"
"P404819299", "You charge at your distant foe causing High Smashing damage to your target and Minor Smashing damage to up to 5 nearby foes.  Affected foes may be knocked off their feet. Flying Strike requires you to have two other powers from the Utility Belt power pool. Damage: High, Recharge: Long"
