# NOTE: MAKE SURE THESE FILES ARE SAVED IN UTF-8 FORMAT!!!  THE GAME MAY CRASH IF YOU DON'T!!!

# NOTE: The EULA text here is for the US.  The UK EULA should be in the eula-uk.ms file.

# NOTE: This is the PC version

# Also, the EU EULA will not be a straight translation of the US version due to legal reasons.

"EulaAgree" : "Accept"

"EulaReject" : "Reject"

"EulaBack" : "Back"

"EulaRejectDialog" : "Not accepting the User Agreement will now close the game."

"EulaText" : <<EulaText>>
