# NOTE: MAKE SURE THESE FILES ARE SAVED IN UTF-8 FORMAT!!!  THE GAME MAY CRASH IF YOU DON'T!!!
# NOTE: This is a UK specific EULA file and the EULA should not be translated.
# NOTE: This is the Mac version
# Translated EULA files should be in eula.ms in each language subfolder.
"EulaAgree-UK" : "Accept"
"EulaReject-UK" : "Reject"
"EulaBack-UK" : "Back"
"EulaRejectDialog-UK" : "Not accepting the User Agreement will now close the game."
"EulaText-UK" : <<EulaText-UK>>
