####################################################################
## Weapons_LeftHandWeild.inc - Sequencers for Left Handed weapons (refer to combat ready state)
####################################################################

Include sequencers\player\Weapons\Weapons_DualWield_Archery.inc
Include sequencers\player\Weapons\Weapons_DualWield_Archery_a.inc
Include sequencers\player\Weapons\Weapons_DualWield_Katana.inc
Include sequencers\player\WEAPONS\Weapons_DualWield_Katana_a.inc