//PLAQUES

//The Future is Today
"NeuronTech" "<face heading><span align=center><font color=orange>The Future is Today</span></face></font>Here is where the future is given birth, through the ingenuity of Praetoria's technological mastermind and guided by the peerless wisdom of the Earth's tireless defender: Emperor Marcus Cole.<br><face heading><span align=center><font color=gold>- - -</span></face></font><br>Together they shall forge a brighter future for us all."

//Keyes Reactor
"AntimatterReactor" "<face heading><font color=orange>Keyes Reactor</face></font>Here lies the cornerstone and foundation of Emperor Cole's vision for a powerful Praetoria: the city's Antimatter Reactor. Generating enough electricity to power ten cities the size of Praetoria or larger, it ensures that the people need never fear the night. </span></face></font> <face heading><span align=center><font color=orange><i>Emperor Marcus Cole: shining the beacon that will light our way to a bright future.</i></span></face></font>"

//Lambda Sector
"LambdaSector" "<face heading><span align=center><font color=orange>Lambda Sector Headquarters of the Guardians of Praetorian Sovereignty</span></face></font><br><br>Great have been the sacrifices made by our armed forces in the struggle against the unceasing hostility perpetuated by all who oppose Praetoria. Behind these walls our sworn defenders train with great dedication of spirit and indomitable strength. Their discipline and dedication to the State and to our exalted Emperor Marcus Cole stands as a shining example for all to follow.<br><br><face heading><span align=center>All hail our selfless defenders!</span></face><br><br></span></face></font> <face heading><span align=center><font color=orange>///WARNING///</span></face></font> <span align=center><face heading><font color=orange>LETHAL FORCE IS AUTHORIZED BEYOND THIS POINT</span></face></font>"

//Resistance Plaque 11
"Resistance11" "<face heading><span align=center><font color=pink>Lesson 11: You ARE Being Watched</span></face></font><br><br>Did you see that person on the street just disappear around the corner?  Where do you think they went?  Maybe they were following you?  Anyone standing around watching you read this right now?  Yeah, chomper, you're finally seeing it."

//Resistance Plaque 12
"Resistance12" "<face heading><span align=center><font color=pink>Lesson 12: Don't Drink the Cole-Aid</span></face></font><br><br>Got yourself a thirst that needs a-quenching?  Chug down a can of Beefy Pop before you even think of slurpin' on that Enriche!  Oh yeah!"

//Resistance Plaque 13
"Resistance13" "<face heading><span align=center><font color=pink>Lesson 13: The Pen IS Mighty, but Swords Leave a Mark</span></face></font><br><br>Papa Vagabond always says 'don't bring a pen to a gunfight.'  Words will never hurt you, but bullets sure will make you all Mister Swiss Cheese.  So get your own and scamp it up!"

//Resistance Plaque 14
"Resistance14" "<face heading><span align=center><font color=pink>Lesson 14: Knowledge is Power</span></face></font><br><br>All those Praetors know this, so you're just gettin' the gristly bits while they're mackin' down on a prime cut of Filet McPower.  The truth - take a look, it's in a book."

//Resistance Plaque 15
"Resistance15" "<face heading><span align=center><font color=pink>Lesson 15: Be the Revolution</span></face></font><br><br>Shut your yaptrap and you'll get pushed outta the way like any other squiggly-zibble.  Johnny, get your spine and take it to the Tyrant!"




