// bumpmapMultiply.fp
// 'BLENDMODE_BUMPMAP_MULTIPLY' material. See shaders.txt for more information

// @todo could use an RGBS (baked lighting) variation of this on BLENDMODE side as well as vertex program
// @todo does this blend mode need to support ultra reflections?

#include "variants.cgh"

/*
 #fragment let slimshady know this is a fragment program
 Variants and options to be verified/analyzed by slimshady script:
	#option BIT_HIGH_QUALITY
	#option	BIT_SHADOWMAP				
	#option	BIT_DEBUG					
*/


#ifdef BIT_HIGH_QUALITY
	#define HIGH_QUALITY
#endif

// definitions required for this program,
// so we don't bother putting them in a variant
#ifdef HIGH_QUALITY
	#define VERTEX_LIT		VERT_COLOR
	#define PIXEL_LIT		BUMP_ALL
#else
	#define VERTEX_LIT		VERT_COLOR
	#define PIXEL_LIT		BUMP_SPEC
#endif

#include "shadows.cgh"
#include "constants_fp.cgh"
#include "functions.cgh"

//--------------------------------------------------
// Input struct def
//--------------------------------------------------
#include "nexus.cgh"			// (#extract) define vertex program structure/semantics <=> fragment program input

#ifndef BIT_DEBUG

uniform sampler2D sampler_base				: TEXUNIT0;
uniform sampler2D sampler_blend				: TEXUNIT1;
uniform sampler2D sampler_normal_gloss		: TEXUNIT2;

//---------------------------------------------------------------------------
//  main
//---------------------------------------------------------------------------
float4 main( VP2FP IN ) : COLOR
{    
	float2 uv0 = IN.uv0_uv1.xy;
	float2 uv1 = IN.uv0_uv1.zw;

	//****
	// populate lighting vectors and tangent basis conversions as necessary
#if defined(HIGH_QUALITY)
    float3 normal_vs	= normalize(IN.normal_vs.xyz);   
	float4 tangent_vs	= float4( normalize(IN.tangent_vs.xyz), IN.tangent_vs.w );	// normalize tangent but keep binormal sign in w
    float3 light_vs		= g_LightDirFP.xyz;	// light direction in view space, should already be normalized
	float3 position_vs	= IN.position_vs.xyz;

	LightingVectorsHQ	light_vectors	= populate_lighting_vectors_hq( normal_vs, tangent_vs, position_vs, light_vs );
	float3				light_ts		= light_vectors.light_ts;
	float3				half_ts			= light_vectors.half_ts;
#else
	float3 light_ts		= normalize(IN.light_ts.xyz);	// renormalize from interpolation
	float3 half_ts		= normalize( normalize(IN.view_ts.xyz) + light_ts );
	#ifdef USE_SHADOWMAP
	float3 position_vs	= IN.position_vs.xyz;
	#endif
#endif

	//****
	// Setup light prop structs with the lighting constants and properties for material 1
	// @todo normal map lookup is a little strange here
	// the old vertex shader sends down uv0 for RGBS pre baked lighting and uv1 otherwise??
    float4 normal_gloss = map_color_to_normal( tex2D( sampler_normal_gloss, uv1) ); // normal in tangent space, also contains gloss map in alpha channel

	#ifdef USE_SHADOWMAP
		// determine fragment raw shadowing factor once up front and apply to all material lighting
		float shade_factor = shadow_csm( position_vs, IN.fragment_pos );
	#else
		float shade_factor = 1; // set to one and compiler will optimize away operations
	#endif

	LightProps light = get_default_light_properties(shade_factor, 1);	// gloss param is 1 here

	//****
	// Calculate the base material color, in this case a simple modulate
	float4 tex_base    = tex2D( sampler_base, uv0 );
    float4 tex_blend   = tex2D( sampler_blend, uv1 );

	float4 out_color	= tex_base * tex_blend;	// straight modulation of base by blend texture (alpha also)
#ifndef HIGH_QUALITY
	out_color.rgb		*= IN.color.rgb;		// modulate by vertex color for vertex lit/baked lighting
#endif
	out_color.rgb		*= 8;					// scale (legacy assets and register combiner programs?)
	out_color.a			*= g_Env0FP.a;			// modulate by lod alpha

    //****
	// Calculate and apply lighting to material
	float3 light_factors = calc_lighting_factors( normal_gloss, light_ts, half_ts, light.spec_color_and_exp.a );

#ifdef HIGH_QUALITY
	// full per pixel ligthing, just like other materials
	#ifdef USE_SHADOWMAP
		light_factors = shadow_light_factors( light_factors, light.shade_factor ); // apply shadow factors to light factors
	#endif
	out_color.rgb = apply_lighting( out_color.rgb, light_factors, light );
#else
	// this material has historically only been applying bumped per pixel specular lighting to the supplied vertex color
	#ifdef USE_SHADOWMAP
		// NOTE: this will result in discrepancy in shadowing with other materials
		// shadow map should generally prefer to use the high quality variant

		// determine shadowing factors for ambient, diffuse and specular
		float3 shadow_factors = calc_shadow_factors( shade_factor, light_factors.y /*saturate(N*L)*/);
		// apply shadow factors to light factors (compiler will optimize away if these are 1 when shadows are not used)
		light_factors *= shadow_factors;
		float3 gloss = saturate( light_factors.z * light.spec_color_and_exp.rgb );

		// In the case of shadows we  to take the lighting down (i.e. just reducing specular
		// isn't going to cut it). So we darken the calculated material/baked vertex lighting.
		// It helps avoid artffacts if darken more according to N*L
		out_color.rgb = out_color.rgb*light_factors.x + gloss;
	#else
		float3 gloss = saturate( light_factors.z * light.spec_color_and_exp.rgb );
		out_color.rgb = out_color.rgb + gloss;
	#endif
#endif

	//****
	// Finally fog color and return
	out_color.rgb = calc_fogged_color( out_color.rgb, IN.fogCoord );

	return out_color;
}
#else
//--------------------------------------------------
// Debug Variant
//--------------------------------------------------

#include "debug.cgh"

float4 main( VP2FP IN ) : COLOR
{
	return debug_common_bumpmap_main( BLENDMODE_BUMPMAP_MULTIPLY, IN );
}
#endif // BIT_DEBUG