/*
 vp_master_legacy.cg

 This is the master vertex program which is conditionally compiled to feed
 legacy hardware register combiner 'program' blend mode material implementations.

 See legacy_shaders.txt for more information.
*/


#include "variants.cgh"				// this include file must come before any #variants for slimshady processing

/*
 Variants to be verified/analyzed by slimshady script:
	#variant fixed_function_unlit.vp    : SKIN=0 LIGHT_SPACE=VIEW   VERTEX_LIT=FF_UNLIT_GL TC_XFORM=TC_MATRIX  PIXEL_LIT=NONE      REFLECT=FAUX_0_1
	#variant fixed_function.vp          : SKIN=0 LIGHT_SPACE=VIEW   VERTEX_LIT=FF_LIT_GL   TC_XFORM=TC_MATRIX  PIXEL_LIT=NONE      REFLECT=FAUX_0_1
	#variant bump.vp                    : SKIN=0 LIGHT_SPACE=MODEL  VERTEX_LIT=DIFFUSE     TC_XFORM=TC_OFFSET  PIXEL_LIT=BUMP_SPEC REFLECT=NONE
	#variant bump_rgb.vp                : SKIN=0 LIGHT_SPACE=MODEL  VERTEX_LIT=PRELIT      TC_XFORM=TC_OFFSET  PIXEL_LIT=BUMP_SPEC REFLECT=NONE
	#variant bump_dual.vp               : SKIN=0 LIGHT_SPACE=VIEW   VERTEX_LIT=NONE        TC_XFORM=NONE       PIXEL_LIT=BUMP_ALL  REFLECT=NONE
	#variant skin.vp                    : SKIN=1 LIGHT_SPACE=VIEW   VERTEX_LIT=DIFFUSE     TC_XFORM=NONE       PIXEL_LIT=NONE      REFLECT=NONE
	#variant skin_bump.vp               : SKIN=1 LIGHT_SPACE=VIEW   VERTEX_LIT=NONE        TC_XFORM=NONE       PIXEL_LIT=BUMP_ALL  REFLECT=NONE
*/

#include "constants_vp.cgh"
#include "functions.cgh"


//--------------------------------------------------
// Vertex Input Attribute Declaration
//--------------------------------------------------
struct vpIn
{
    float4 attr_position		: POSITION;
    float3 attr_normal			: NORMAL;
#if VERTEX_LIT == VERT_COLOR || VERTEX_LIT == FF_UNLIT_GL || VERTEX_LIT == FF_LIT_GL
    float4 attr_color			: COLOR;
#endif
	float4 attr_texCoord0		: TEXCOORD0;
    float4 attr_texCoord1		: TEXCOORD1;
#if PIXEL_LIT >= BUMP_SPEC
    float4 attr_tangent			: ATTR7;		// binormal sign is stored in w component
#endif
#if SKIN
    float4 boneWeights          : ATTR1;        // vertex.attrib[1];
    float4 boneIndices          : ATTR5;        // vertex.attrib[5];
#endif
#if VERTEX_LIT == PRELIT
    float4 attr_prelit_color	: ATTR11;		// 	@todo could change the runtime to make this come in on attr_color?
#endif
};

//--------------------------------------------------
// Vertex Output Declaration
// !! DO NOT CHANGE !! - Unless you also update register combiner logic
//--------------------------------------------------
struct vpOutput
{
    float4 position : POSITION;
#if VERTEX_LIT != NONE				
    float4 color    : COLOR;			// NOTE: resource can also be used by per pixel bump light vector below, either is exclusive
#endif
	float  fogCoord : FOG;
    float4 uv0      : TEXCOORD0;
    float4 uv1      : TEXCOORD1;

#if PIXEL_LIT != NONE
    float4 uv2      : TEXCOORD2;		// used to lookup normal map on tex unit 2
	// interpolants for per pixel lighting (gl tex env combiner programs do not support per pixel bump mapping)
	#if defined(NV1X) | defined(NV2X)		// nVidia register combiner path
		float4 half_ts_rc		: COLOR1;
		#if PIXEL_LIT == BUMP_ALL
			float4 light_ts_rc	: COLOR;
		#endif
	#elif defined( R200 )					// ATI register combiner path
		float4 half_ts		: TEXCOORD3;
		#if PIXEL_LIT == BUMP_ALL
			float4 light_ts	: TEXCOORD4;
		#endif
	#endif
#endif // PIXEL_LIT
};

//-----------------------------------------------------------------------------
// Vertex Programs Variants
//-----------------------------------------------------------------------------

vpOutput main( vpIn IN )
{
    vpOutput OUT;

	// Transform inputs to the correct working space, e.g. view space or model space

    //-----------------------
	// Position
#if SKIN
	// Skinning
	// skinning matrices skin directly to view space

    // bone indices are *3 for ARB bone matrix indices
	// @todo these will just be set as matrix uniforms when runtime is updated
	int iBone0 = IN.boneIndices.x;	
	int iBone1 = IN.boneIndices.y;
    float3x4 boneMatrix0 = float3x4(
                                g_BoneMatrixArrVP[iBone0+0],
                                g_BoneMatrixArrVP[iBone0+1],
                                g_BoneMatrixArrVP[iBone0+2] );
    float3x4 boneMatrix1 = float3x4(
                                g_BoneMatrixArrVP[iBone1+0],
                                g_BoneMatrixArrVP[iBone1+1],
                                g_BoneMatrixArrVP[iBone1+2] );

    // blend values between bone 0 & 1
	float weight = IN.boneWeights.y;	// @todo only necessary to send a single weight in the vertex stream
	float3 position_vs	= blend_bone_positions(	IN.attr_position, boneMatrix0, boneMatrix1, weight ).xyz;
#else
    // Transform position to view space
    float3 position_vs = mul( (float3x4) g_ModelViewMatrix, IN.attr_position);
#endif

	//****
	// Calculate homogeneous clipspace position coordinates
	OUT.position = mul( g_ProjectionMatrix, float4(position_vs,1) );

	//****
    // Compute fog coordinate, avoid sqrt( <= 0 )
    OUT.fogCoord = sqrt( dot(position_vs, position_vs) + 1e-16);

    //-----------------------
	// Calculate base and blend texture coordinates
#if TC_XFORM == TC_OFFSET
	OUT.uv0	= ( g_TexScroll0VP + IN.attr_texCoord0 );
    OUT.uv1	= ( g_TexScroll1VP + IN.attr_texCoord1 );
#elif TC_XFORM == TC_MATRIX
	OUT.uv0 = mul( g_TextureMatrix0, IN.attr_texCoord0 );
	OUT.uv1 = mul( g_TextureMatrix1, IN.attr_texCoord1 );
#else	// TC_XFORM == NONE
	OUT.uv0	= IN.attr_texCoord0;
    OUT.uv1	= IN.attr_texCoord1;
#endif

    //-----------------------
	// Establish basic lighting vectors
	float3 normal, light, view;

#if VERTEX_LIT == FF_LIT_GL || (VERTEX_LIT == FF_UNLIT_GL && REFLECT != NONE)
	// GL lighting vectors are supplied in view space
	// fixed function has its own variable g_Light0PositionVP which is shadowing state.light[0].position
	// All other vertex shaders use a different constant g_LightDirVP
	// @todo Change the runtime to just set g_LightDirVP in both cases if this isn't already done?
	// @todo g_LightDirVP looks like it is either view space or model space depending on DRAWMODE?

	// We also do this for the FF_UNLIT_GL so that the normal and view vector get calculated in the same space as
	// expected by the faux reflection calculation
	light = g_Light0PositionVP.xyz;	// @todo shader code expects this is already normalized, check
#else
	light	= g_LightDirVP.xyz;				// already in view space for skinned models? @todo also normalized?
#endif

#if LIGHT_SPACE == MODEL
	// Compute lighting vectors in model space (attribute normal is already in model space)
	normal	= IN.attr_normal.xyz;
    light	= normalize( light - IN.attr_position.xyz );
	view	= normalize( g_ViewerPositionVP.xyz - IN.attr_position.xyz ); // view vector in model space (vector to eye)
#else // most common case is VIEW space lighting
	#if SKIN
		// lighting vectors are in view space for skinned models
		normal	= blend_bone_normals( IN.attr_normal.xyz, boneMatrix0, boneMatrix1, weight );
	#else
		normal = normalize(mul( (float3x3) g_ModelViewMatrix, IN.attr_normal.xyz));
	#endif
	view = normalize( -position_vs );	// view vector in view space (vector to eye) is just reverse of position vector
#endif


	//-----------------------
    // Calculate vertex lighting
#if VERTEX_LIT == VERT_COLOR || VERTEX_LIT == FF_UNLIT_GL
	// use color supplied in the input COLOR attribute
	OUT.color = IN.attr_color;
#elif VERTEX_LIT == PRELIT
	// use prelit baked on lighting supplied with vertex
	// @todo could change the runtime to make this same as above by passing to COLOR instead of ATTR11
	OUT.color = IN.attr_prelit_color;
#elif VERTEX_LIT == DIFFUSE
	// Compute diffuse + ambient lighting per vertex (sepcular will be per pixel bumped)
	OUT.color = saturate( dot( normal, light)) * g_DiffuseParameterVP + g_AmbientParameterVP;	
#elif VERTEX_LIT == FF_LIT_GL
	// emulate OpenGL fixed function lighting using gl state for light and material shinniness
	{
        float3 H_vs = normalize( light + view );

        // Compute diffuse and specular dot products and use LIT to compute
        // lighting coefficients.
        float NdotL = dot(normal, light);
        float NdotH = dot(normal, H_vs);
        float4 dots = lit( NdotL, NdotH, g_MaterialShininessVP.x );

        // Accumulate color contributions.
        float4 lightAccum = (( dots.y * g_Light0DiffuseVP ) + g_Light0AmbientVP );

        float Lum = max(0, dot(normal, -light));	// @todo diffuse reverse? remove
        lightAccum += ( Lum * g_Light1DiffuseVP );
        lightAccum *= IN.attr_color;

        OUT.color.xyz = (( dots.z * g_Light0SpecularVP ) + lightAccum ).xyz;
        OUT.color.w = IN.attr_color.w;
	}
#endif	//VERTEX_LIT == NONE

    //-----------------------
    // Reflection data generation and selection
#if REFLECT == FAUX_0_1
    float2 uvFaux = calc_faux_reflection_uv( normal, position_vs );
    // g_ReflectionParamVP is a selector set by the material that chooses either
    // vertex supplied texture coordinates or the faux reflection map uv coordinates
    OUT.uv0.xy = (( g_ReflectionParamVP.z * OUT.uv0.xy ) + ( uvFaux * g_ReflectionParamVP.x ) );
    OUT.uv1.xy = (( g_ReflectionParamVP.w * OUT.uv1.xy ) + ( uvFaux * g_ReflectionParamVP.y ) );
#elif REFLECT == FAUX_0_0
    float2 uvFaux = calc_faux_reflection_uv( normal, position_vs );
    // g_ReflectionParamVP is a selector set by the material that chooses either
    // vertex supplied texture coordinates or the faux reflection map uv coordinates
    OUT.uv0.xy = (( g_ReflectionParamVP.z * OUT.uv0.xy ) + ( uvFaux * g_ReflectionParamVP.x ) );
    OUT.uv1.xy = (( g_ReflectionParamVP.w * OUT.uv0.xy ) + ( uvFaux * g_ReflectionParamVP.y ) );
#endif

#if PIXEL_LIT != NONE
    //-----------------------
    // Calculate interpolants for per-pixel bump mapped lighting
    // Calculate interpolants for per-pixel bump mapped lighting
	float3 tangent	= IN.attr_tangent.xyz;	// model space tangent from geo
	#if LIGHT_SPACE == VIEW
		#if SKIN
			// lighting vectors xform into view space for skinned models
			tangent	= blend_bone_normals( tangent, boneMatrix0, boneMatrix1, weight );
		#else
			tangent = normalize(mul( (float3x3) g_ModelViewMatrix, IN.attr_tangent.xyz));
		#endif
	#endif

	// Calculate light and half vector in tangent space to supply fragment program
	float3 o_half_ts, o_light_ts;
	calc_tangent_space_light_and_half( normal, tangent, sign(IN.attr_tangent.w), view, light, o_half_ts, o_light_ts );

	// Select the right output semantic based on target register combiner program
	// (gl tex env combiner programs do not support per pixel bump mapping)
	#if defined(NV1X) | defined(NV2X)
		// range compress (from [-1, 1] to [0, 1]) tangent space vectors into the COLOR output interplators expected by combiner programs
		OUT.half_ts_rc		= float4(range_compress(o_half_ts), 0);
		#if PIXEL_LIT == BUMP_ALL
			OUT.light_ts_rc	= float4(range_compress(o_light_ts), 0);
		#endif
	#elif defined( R200 )
		OUT.half_ts			= float4(o_half_ts,0);
		#if PIXEL_LIT == BUMP_ALL
			OUT.light_ts	= float4(o_light_ts, 0);
		#endif
	#endif

	#if VERTEX_LIT == DIFFUSE && PIXEL_LIT == BUMP_SPEC
	// @todo ARB bump_rgbs.vp copies uv0 to uv2 (like all the others) but bump.vp copies uv1 to uv2. Is that correct
		OUT.uv2	= OUT.uv1;	// register combiner programs sample bump texture from the TEXUNITs matching TEXCOORD
	#else
		OUT.uv2	= OUT.uv0;	// register combiner programs sample bump texture from the TEXUNITs matching TEXCOORD
	#endif
#endif // PIXEL_LIT != NONE

	return OUT;
}
